#!/bin/bash
#  IPT-CONF small configuration framework to handle configuration of linux iptables netfilter.
#  Copyright (C) 2011 Robert Vojcik
#  
#  This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#  
#  Contact
#  -------
#  Robert Vojcik ( robert@vojcik.net )

. /etc/ipt.conf

command=$1
shift

case $command in 

"add")
	$BINDIR/firewall-addrule.sh $@
;;
"del")
	$BINDIR/firewall-rmrule.sh $@
;;
"detect")
	$BINDIR/firewall-detect.sh $@
;;
"status")
	ls -1 $CONFDIR/rules.enabled/ | grep -e ".rule$"
;;
"stop")
	$BINDIR/firewall-stop.sh
;;
"detect")
	$BINDIR/firewall-detect.sh $@
;;
"start")
	$BINDIR/firewall-start.sh
;;
"restart")
	$BINDIR/firewall-stop.sh
	$BINDIR/firewall-start.sh
;;
*)
	echo -e "\nUsage: $0 <add|del|status|detect|stop|start|restart|init> [rule1] [rule2] ...\n"
;;

esac
