#!/bin/bash
#
# ipt-conf project
#
# Main control wrapper
# Robert Vojcik ( vojcik@gmail.com )

. /etc/ipt.conf

command=$1
shift

case $command in 

"add")
	$BINDIR/firewall-addrule.sh $@
;;
"del")
	$BINDIR/firewall-rmrule.sh $@
;;
"detect")
	$BINDIR/firewall-detect.sh $@
;;
"status")
	ls -1 $CONFDIR/rules.enabled/ | grep -e ".rule$"
;;
"stop")
	$BINDIR/firewall-stop.sh
;;
"detect")
	$BINDIR/firewall-detect.sh $@
;;
"start")
	$BINDIR/firewall-start.sh
;;
"restart")
	$BINDIR/firewall-stop.sh
	$BINDIR/firewall-start.sh
;;
*)
	echo -e "\nUsage: $0 <add|del|status|detect|stop|start|restart|init> [rule1] [rule2] ...\n"
;;

esac
